-- ============================================================================
-- CoreStone Technologies — Oracle Database
-- tables.sql
--
-- Target: Oracle Database 19c+ (Autonomous DB / Oracle XE / on-prem all
-- supported — nothing here uses a feature newer than 19c).
--
-- Column-for-column match against backend/app/models/*.py. If you change a
-- SQLAlchemy model, mirror the change here — there is no ORM migration
-- auto-sync in this project; Alembic (see backend/alembic/) is the source
-- of truth for incremental changes, this file is the from-scratch DDL.
--
-- Primary keys use Oracle 12c+ IDENTITY columns (GENERATED BY DEFAULT AS
-- IDENTITY), matching what SQLAlchemy's oracledb dialect generates for an
-- `autoincrement=True` Integer primary key — no separate PK sequence or
-- BEFORE INSERT trigger is needed for surrogate keys.
--
-- Oracle has no native BOOLEAN prior to 23c: is_active/is_active-style
-- flags use NUMBER(1) with a CHECK (col IN (0,1)) constraint instead,
-- applied in constraints.sql.
--
-- Run order: tables.sql -> sequences.sql -> constraints.sql -> indexes.sql
--            -> functions.sql -> procedures.sql -> triggers.sql -> views.sql
--            -> sample_data.sql   (see schema.sql, which runs all of these
--            in this exact order)
-- ============================================================================

-- ----------------------------------------------------------------------------
-- BUSINESS_CATEGORIES  (industries — Nurseries, Retail, Hospitals, ...)
-- ----------------------------------------------------------------------------
CREATE TABLE BUSINESS_CATEGORIES (
    ID              NUMBER          GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    SLUG            VARCHAR2(120)   NOT NULL,
    NAME            VARCHAR2(160)   NOT NULL,
    DESCRIPTION     CLOB,
    IS_ACTIVE       NUMBER(1)       DEFAULT 1 NOT NULL,
    CREATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_BUSINESS_CATEGORIES PRIMARY KEY (ID)
);

COMMENT ON TABLE BUSINESS_CATEGORIES IS 'Industry categories shown on the Industries pages (retail, hospitals, pharmacies, ...).';

-- ----------------------------------------------------------------------------
-- SERVICES  (solutions — Billing Software, GST Billing, ...)
-- ----------------------------------------------------------------------------
CREATE TABLE SERVICES (
    ID              NUMBER          GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    CATEGORY_ID     NUMBER,
    SLUG            VARCHAR2(120)   NOT NULL,
    NAME            VARCHAR2(160)   NOT NULL,
    DESCRIPTION     CLOB,
    IS_ACTIVE       NUMBER(1)       DEFAULT 1 NOT NULL,
    CREATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_SERVICES PRIMARY KEY (ID)
);

COMMENT ON TABLE SERVICES IS 'Solution offerings shown on the Solutions pages (billing, inventory, GST, ...).';

-- ----------------------------------------------------------------------------
-- SOFTWARE_FEATURES  (feature line items, optionally attached to a service)
-- ----------------------------------------------------------------------------
CREATE TABLE SOFTWARE_FEATURES (
    ID              NUMBER          GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    SERVICE_ID      NUMBER,
    NAME            VARCHAR2(160)   NOT NULL,
    DESCRIPTION     CLOB,
    CREATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_SOFTWARE_FEATURES PRIMARY KEY (ID)
);

-- ----------------------------------------------------------------------------
-- CUSTOMER_LEADS  (parent record for every enquiry)
-- ----------------------------------------------------------------------------
CREATE TABLE CUSTOMER_LEADS (
    ID              NUMBER          GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    LEAD_ID         VARCHAR2(32)    NOT NULL,
    FULL_NAME       VARCHAR2(160)   NOT NULL,
    EMAIL           VARCHAR2(255)   NOT NULL,
    PHONE           VARCHAR2(20)    NOT NULL,
    MESSAGE         CLOB,
    SOURCE          VARCHAR2(32)    NOT NULL,
    STATUS          VARCHAR2(32)    DEFAULT 'new' NOT NULL,
    -- Preferred language the customer submitted in ('en' | 'ta') so admin
    -- staff and any future automated WhatsApp/email follow-up reply in
    -- the language the customer actually used.
    PREFERRED_LANGUAGE VARCHAR2(5)  DEFAULT 'en' NOT NULL,
    CREATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_CUSTOMER_LEADS PRIMARY KEY (ID)
);

COMMENT ON TABLE CUSTOMER_LEADS IS 'Parent enquiry record — every contact-form submission and demo request creates one row here.';

-- ----------------------------------------------------------------------------
-- DEMO_REQUESTS  (one-to-one extension of CUSTOMER_LEADS)
-- ----------------------------------------------------------------------------
CREATE TABLE DEMO_REQUESTS (
    ID                      NUMBER          GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    LEAD_ID                 NUMBER          NOT NULL,
    COMPANY_NAME            VARCHAR2(200)   NOT NULL,
    BUSINESS_TYPE           VARCHAR2(60)    NOT NULL,
    INDUSTRY                VARCHAR2(80)    NOT NULL,
    CITY                    VARCHAR2(100)   NOT NULL,
    STATE                   VARCHAR2(100)   NOT NULL,
    BUSINESS_REQUIREMENT    CLOB            NOT NULL,
    PREFERRED_DEMO_DATE     DATE            NOT NULL,
    PREFERRED_DEMO_TIME     VARCHAR2(10)    NOT NULL,
    DEMO_MODE               VARCHAR2(20)    NOT NULL,
    CREATED_AT              TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT              TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_DEMO_REQUESTS PRIMARY KEY (ID)
);

-- ----------------------------------------------------------------------------
-- LEAD_FOLLOWUPS  (follow-up tasks/notes managed from the APEX admin portal)
-- ----------------------------------------------------------------------------
CREATE TABLE LEAD_FOLLOWUPS (
    ID                      NUMBER          GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    LEAD_ID                 NUMBER          NOT NULL,
    NOTE                    CLOB            NOT NULL,
    FOLLOW_UP_DATE          DATE            NOT NULL,
    STATUS                  VARCHAR2(20)    DEFAULT 'pending' NOT NULL,
    CREATED_BY_ADMIN_ID     NUMBER,
    CREATED_AT              TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT              TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_LEAD_FOLLOWUPS PRIMARY KEY (ID)
);

-- ----------------------------------------------------------------------------
-- WHATSAPP_MESSAGES  (stored WhatsApp communication history per lead)
-- ----------------------------------------------------------------------------
CREATE TABLE WHATSAPP_MESSAGES (
    ID              NUMBER          GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    LEAD_ID         NUMBER          NOT NULL,
    DIRECTION       VARCHAR2(10)    NOT NULL,
    MESSAGE_TEXT    CLOB            NOT NULL,
    -- Language the stored message was sent/received in ('en' | 'ta').
    LANGUAGE_CODE   VARCHAR2(5)     DEFAULT 'en' NOT NULL,
    CREATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_WHATSAPP_MESSAGES PRIMARY KEY (ID)
);

-- ----------------------------------------------------------------------------
-- ADMIN_USERS  (Oracle APEX admin portal + JWT API authentication)
-- ----------------------------------------------------------------------------
CREATE TABLE ADMIN_USERS (
    ID                  NUMBER          GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    FULL_NAME           VARCHAR2(160)   NOT NULL,
    EMAIL               VARCHAR2(255)   NOT NULL,
    HASHED_PASSWORD     VARCHAR2(255)   NOT NULL,
    ROLE                VARCHAR2(20)    DEFAULT 'support_agent' NOT NULL,
    IS_ACTIVE           NUMBER(1)       DEFAULT 1 NOT NULL,
    CREATED_AT          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_ADMIN_USERS PRIMARY KEY (ID)
);

-- ----------------------------------------------------------------------------
-- ADMIN_REFRESH_TOKENS  (server-side revocable JWT refresh tokens)
-- ----------------------------------------------------------------------------
CREATE TABLE ADMIN_REFRESH_TOKENS (
    ID              NUMBER          GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    ADMIN_ID        NUMBER          NOT NULL,
    TOKEN_HASH      VARCHAR2(64)    NOT NULL,
    EXPIRES_AT      TIMESTAMP WITH TIME ZONE NOT NULL,
    REVOKED_AT      TIMESTAMP WITH TIME ZONE,
    CREATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_ADMIN_REFRESH_TOKENS PRIMARY KEY (ID)
);
